# name: Docker Image CI

# on:
#   push:
#     branches: [ "main" ]
# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/build-push-action@v3
#       - name: Build the Docker image
#         run: docker build . --file Dockerfile --tag vuets-nginx:$(date +%s)
