name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    name: Test on Node
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: bengotch/simplewhale:latest
      -
        name: npm install, build and test
        run: |
            npm install
            npm run build --if-present
            npm test
